# Generated by Django 5.0.1 on 2024-02-13 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented',
            name='expected_return',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 17, 40, 36, 154892, tzinfo=datetime.timezone.utc)),
        ),
    ]
