# Generated by Django 5.0.1 on 2024-02-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_presence_in_class_presenceinclass_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='school_supplie',
            new_name='school_subject',
        ),
        migrations.RenameField(
            model_name='testscore',
            old_name='school_supplies',
            new_name='school_subject',
        ),
        migrations.AddField(
            model_name='presenceinclass',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolroom',
            name='end_class',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolroom',
            name='name',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolroom',
            name='start_class',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
