# Generated by Django 5.0.1 on 2024-02-15 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_serie_schoolserie_ano_schoolserie_grau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented',
            name='expected_return',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 13, 39, 37, 936428, tzinfo=datetime.timezone.utc)),
        ),
    ]
