# Generated by Django 5.0.1 on 2024-02-09 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_schoolroom_end_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscore',
            name='grade',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='testscore',
            name='month',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='testscore',
            name='type',
            field=models.CharField(choices=[(0, 'Monthly'), (1, 'bimonthly'), (2, 'bimonthly recovery'), (3, 'semi-annual recovery')], default=0),
        ),
        migrations.AddField(
            model_name='testscore',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
