# Generated by Django 5.0.1 on 2024-02-15 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_rented_expected_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented',
            name='expected_return',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 14, 7, 2, 128169, tzinfo=datetime.timezone.utc)),
        ),
    ]
