# Generated by Django 5.0.1 on 2024-02-12 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_book_remove_student_rented_rented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='entre_date',
            new_name='entry_date',
        ),
        migrations.AlterField(
            model_name='rented',
            name='expected_return',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 14, 23, 58, 966458, tzinfo=datetime.timezone.utc)),
        ),
    ]
