# Generated by Django 5.0.1 on 2024-02-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_logger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logger',
            options={'permissions': [('persons.view_logger', 'Can view Logger')]},
        ),
    ]
